apiVersion: v1
data:
  mimir-config.yaml: |
    multitenancy_enabled: false
    target: all
    common:
      storage:
        backend: s3
        s3:
          bucket_name: <bucket_name>
          endpoint: s3.ap-south-1.amazonaws.com
          region: ap-south-1
    blocks_storage:
      storage_prefix: blocks
    ruler_storage:
      storage_prefix: ruler
    alertmanager_storage:
      storage_prefix: alertmanager
    ingester:
      ring:
        replication_factor: 1
    store_gateway:
      sharding_ring:
        replication_factor: 1
    alertmanager:
      sharding_ring:
        replication_factor: 1
    limits:
      max_label_names_per_series: 35
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mimir-config
  namespace: observability
